apiVersion: v2
name: access-control
description: A Helm chart for access-control service

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"

kubeVersion: ">= 1.21.0"

dependencies:
  - name: strimzi-kafka-operator
    version: 0.27.1
    repository: https://strimzi.io/charts/
  - name: cassandra
    version: 9.1.5
    repository: https://charts.bitnami.com/bitnami/


# apiVersion: The chart API version (required)
# name: The name of the chart (required)
# version: A SemVer 2 version (required)
# kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
# description: A single-sentence description of this project (optional)
# type: The type of the chart (optional)
# keywords:
#   - A list of keywords about this project (optional)
# home: The URL of this projects home page (optional)
# sources:
#   - A list of URLs to source code for this project (optional)
# dependencies: # A list of the chart requirements (optional)
#   - name: The name of the chart (nginx)
#     version: The version of the chart ("1.2.3")
#     repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
#     condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
#     tags: # (optional)
#       - Tags can be used to group charts for enabling/disabling together
#     import-values: # (optional)
#       - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
#     alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
# maintainers: # (optional)
#   - name: The maintainers name (required for each maintainer)
#     email: The maintainers email (optional for each maintainer)
#     url: A URL for the maintainer (optional for each maintainer)
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
# appVersion: The version of the app that this contains (optional). Needn't be SemVer. Quotes recommended.
# deprecated: Whether this chart is deprecated (optional, boolean)
# annotations:
#   example: A list of annotations keyed by name (optional).
