apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "access-control.kafka.name" . }}
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.replicaCount }}
    listeners:
      - name: plain
        port: {{ .Values.kafka.port }}
        type: internal
        tls: false
      - name: tls
        port: {{ .Values.kafka.tlsPort }}
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: {{ .Values.kafka.persistentSize }}
          deleteClaim: false
  zookeeper:
    replicas: {{ .Values.kafka.zookeeper.replicaCount }}
    storage:
      type: persistent-claim
      size:  {{ .Values.kafka.zookeeper.persistentSize }}
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
